#+ID: 32b32aa5-40cf-48c7-ac61-95e94eaa28a9
#+TITLE: Type Theory
#+DATE: 2026-02-12
#+CITE_EXPORT: csl ieee.csl
#+LICENSE: https://creativecommons.org/licenses/by-nc-sa/4.0 CC-BY-NC-SA-4.0
#+STATUS: Draft

#+begin_abstract
TODO
#+end_abstract

* TODO Introduction

* TODO Objective

- Define a language precise enough to so that translating to a programming language
  is feasable, but simple enough so that we understand each others.

- If anything is ambiguous, please send a suggestion.

* :≡

#+ID: 9bfb7073-0f1f-4d3d-a6f2-3fb591502de6
#+begin_definition
/x :≡ y/ means that /x/ is a new name and that for now on, whenever one reads /x/, one
may replace /x/ by /y/.
#+end_definition

#+ID: 86e106a5-122e-4d76-820a-915bc6759ef7
#+begin_instance
If x :≡ 1, then « x + x » may be read as « 1 + 1 ».

If x :≡ azerty, then « x + x » may be read as « azerty + azerty ».

If x :≡ '1', then « x + x » may be read as « '1' + '1' ».
#+end_instance

* ≡

#+ID: 2f301d3a-85c4-4a5e-82f0-f6c4e70eaf49
#+begin_definition
/x ≡ y/ means that whenever one read /x/, one may replace /x/ by y as it was already
introduced before using /:≡/.
#+end_definition

* 🞎

#+ID: 610ac86b-3cd3-4c80-abcf-798e8d134b73
#+begin_definition
*🞎* is a "hole" to be completed.
#+end_definition

#+ID: 2472ec67-394e-4063-ae09-d4af457a4b1b
#+begin_instance
#+begin_example
string : ℕ → String :≡ 🞎
#+end_example
#+end_instance

* …

#+ID: 275d431a-a4bd-4646-8c55-bb284e48a373
#+begin_definition
*…* means that something is implicit and correctly typed.
#+end_definition

#+ID: 88c9a416-332e-4f3d-b174-ba7041bbfb74
#+begin_instance
#+begin_example
string : ℕ → String :≡ …
#+end_example
#+end_instance

* X → Y

#+ID: 2cd5a5e7-8e7f-4bd3-8883-ea557bff0fd7
#+begin_definition
*Why*

We want to express the fact that there is a /way/ to /start from here/ and /get
to there/.

For instance, given a number, say /0/, there is a unique string representation "0". So,
we say: /string(0) :≡ "0"/.

More over, if we call our numbers ℕ, then for all n : ℕ, we have /string(n) : String/.

We may see /string/ as the name of a path, /i.e./ a way, to get from ℕ to String.


*Formation*

#+begin_example
X, Y : Type
X → Y : Type
#+end_example


*Introduction*

#+begin_example
x : X, y is a formula such that y(x) : Y
λx.y : X → Y
x ↦ y :≡ λx.y
#+end_example


*Elimination*

#+begin_example
f : X → Y
x : X
f(x) : Y :≡ (λx.y)(x)
#+end_example
#+end_definition

* Π(x:X),Y(x)

#+ID: 365c0a57-4438-4cca-926f-a65cd3b27b0f
#+begin_definition
*Why*

We want to express the fact that there is a /way/ to /start from here/ and /get
to there/ ; but the place we end up depends on where we start.

For instance, we might want to start from ℕ and end up in String or ℕ depending on
where we started from.

For instance, if n is even, then f(n) :≡ n and if n is odd, then f(n) :≡ string(n).

*Formation*

#+begin_example
Y : X → Type
Π(x:X),Y(x) : Type
#+end_example

*Introduction*

#+begin_example
Y : X → Type
x : X
y formula such that y(x) : Y(x)
λx.y : Π(x:X),Y(x)
#+end_example


*Elimination*

#+begin_example
f : Π(x:X),Y(x)
x : X
f(x) : Y(x) :≡ (λx.y)(x)
#+end_example
#+end_definition

* ∘

#+ID: f920cd27-4343-4c81-99c7-8c7af1d235b3
#+begin_definition
Standard function composition.

#+begin_example
∘ : (A → B) (B → C) → A → C :≡ f g a ↦ g(f(a))
#+end_example
#+end_definition

* ▸

#+ID: 9070801a-3bad-4338-9f8e-c2e0a913a8b6
#+begin_definition
We want to define "pipelines" of transformations that can be read left to right.

#+begin_example
▸ : (A → B) (B → C) → A → C :≡ f g ↦ g ∘ f
a ▸ f ▸ g :≡ ▸(f g)(a)
#+end_example
#+end_definition

#+ID: 4e585c2f-19df-454d-b488-a6fe041680eb
#+begin_instance
#+begin_example
2× : ℕ → ℕ :≡ n ↦ 2 × n
string : ℕ → String :≡ …
f :≡ 2× ▸ string
f : ℕ → String
f(1) = "2"
#+end_example
#+end_instance

* X × Y

#+ID: db863799-1f4f-47f0-af17-6580df6b1c9d
#+begin_definition
*Why*

Given two types of instances X and Y, we might want to consider both instances at the
same time.

For instance, we might want to speak about the pair Capital and Country like Paris
and France at the same time.


*Formation*

#+begin_example
X, Y : Type
X × Y : Type
#+end_example


*Introduction*

#+begin_example
< , > : X Y → X × Y
#+end_example


*Elimination*

#+begin_example
f : X → Y → Z
φ : X × Y → Z :≡ <x, y> ↦ f(x)(y)
#+end_example


-----


#+begin_example
C : X × Y → Type
f : Π(x:X,y:Y),C(<x,y>)
φ : Π(p:X×Y),C(p) :≡ <x, y> ↦ f(x)(y)
#+end_example
#+end_definition

* Σ(x:X),Y(x)

#+ID: 7c6924f4-a505-4d57-a025-461c8f9bd5cc
#+begin_definition
*Why*

We want instances of some type such that they represent a pair of instances where the
second instance type depends on the first instance.

For instance, we might want to speak about pairs such that the second components is a
string if the firt component is an even number.


*Formation*

#+begin_example
X : Type
Y : X → Type
Σ(x:X),Y(x) : Type
#+end_example


*Introduction*

#+begin_example
< , > : x:X Y(x) → Σ(x:X),Y(x)
#+end_example


*Elimination*

#+begin_example
f : Π(x:X),Y(x) → Z
φ : Σ(x:X),Y(x) → Z :≡ <x, y> ↦ f(x)(y)
#+end_example


-----


#+begin_example
C : Π(x:X),Y(x) → Type
f : Π(x:X) Π(y:Y(x)) C(<x,y>)
φ : Π(p:Π(x:X),Y(x)),C(p) :≡ <x, y> ↦ f(x)(y)
#+end_example
#+end_definition

* Magma

#+ID: 9557444e-c534-425c-aff4-bee8376aa957
#+begin_definition
#+begin_example
Magma :≡ Σ(A:Type)(A → A → A)
#+end_example
#+end_definition

* PointedMagma

#+ID: 658ca757-2a6b-49e0-935c-3d1dacf30799
#+begin_definition
#+begin_example
PointedMagma :≡ Σ(A:Type)(A → A → A) × A
#+end_example
#+end_definition

* X + Y

#+ID: 6e00b58e-0ffb-4e6a-af80-26ce98049025
#+begin_definition
*Why*

Given two types X and Y, we might want to consider an instance that may be of one type or the
other.

For instance, we might want to speak about a Capital or a Country like Paris
or France.


*Formation*

#+begin_example
X, Y : Type
X + Y : Type
#+end_example


*Introduction*

#+begin_example
left : X → X + Y
right : Y → X + Y
#+end_example


*Elimination*

#+begin_example
elim : (f : X → Z) (g : Y → Z) → X + Y → Z :≡
  left(x) ↦ f(x)
  right(y) ↦ g(y)
#+end_example


-----


#+begin_example
Target :≡ X + Y → Type
Left : Target → Type :≡ C ↦ Π(x:X),C((left(x)))
Right : Target → Type :≡ C ↦ Π(y:Y),C((right(y)))
ind : C:Target Left(C) Right(C) → Π(p:X+Y),C(p) :≡
  left(x) ↦ f(x)
  right(y) ↦ g(y)
#+end_example
#+end_definition

As long as there are no ambiguities, we will use the following for conciseness:

#+begin_example
a : A + B
b : A + B
c : A + B + C
…
#+end_example

* ℕ

#+ID: 6e6069cd-adf1-4f69-a95d-abfed657fd3d
#+begin_definition
*Why*

We want to be able to count things.


*Formation*

#+begin_example
ℕ : Type
#+end_example


*Introduction*

#+begin_example
0 : ℕ
succ : ℕ → ℕ
n+1 :≡ succ(n)
#+end_example


*Elimination*

#+begin_example
T  : Type
elim : t:T → (next : ℕ T → T) → ℕ → T :≡
  0 ↦ t
  n+1 ↦ next n f(n)
#+end_example


-----


#+begin_example
P : ℕ → Type
Init :≡ P(0)
Step :≡ ℕ P(n) → P(n+1)
ind : (t0 : Init) (step : Step) → Π(n:ℕ),P(n) :≡
  0 ↦ t0
  n+1 ↦ step n f(n)
#+end_example
#+end_definition

* 𝟙

#+ID: c7aa7121-4c0b-45df-b4b4-f54ae7e25302
#+begin_definition
*Why*

We need to have a type that has one element, to represent True.


*Formation*

#+begin_example
𝟙 : Type
#+end_example


*Introduction*

#+begin_example
x : 𝟙
#+end_example


*Elimination*

#+begin_example
C : Type
elim : (c:C) 𝟙 → C :≡ x ↦ c
#+end_example


-----


#+begin_example
ind : (C : 𝟙 → Type) (c : C(x)) → Π(x:𝟙), C(x) :≡ x ↦ c
#+end_example
#+end_definition

* 𝟘

#+ID: cce4d081-7347-492e-abc8-4035ede3b6d3
#+begin_definition
*Why*

We need to have a type that has no element, which is used to represent falsity.


*Formation*

#+begin_example
𝟘 : Type
#+end_example


*Introduction*


*Elimination*

#+begin_example
C : Type
f : 𝟘 → C
#+end_example

-----


#+begin_example
C : 𝟘 → Type
f : Π(x:𝟘), C(x)
#+end_example
#+end_definition

* Boolean

#+ID: e1c1c6ae-32b7-40aa-a917-88b75502120a
#+begin_definition
*Why*

We need to represents booleans /i.e./ a type with two elements, true or false.


*Formation*

#+begin_example
Boolean : Type
#+end_example


*Introduction*

#+begin_example
0 : Boolean
1 : Boolean
#+end_example


*Elimination*

#+begin_example
C : Type
elim : (c0:C) (c1:C) → Boolean → C :≡
  0 ↦ c0
  1 ↦ c1
#+end_example


-----


#+begin_example
C : Boolean → Type
ind : (c0:C(0)) (c1:C(1)) → Π(x:Boolean), C(x) :≡
  0 ↦ c0
  1 ↦ c1
#+end_example
#+end_definition

* Symbol

#+ID: 8b9b2a1c-baf4-4e1b-856a-704ff98d04fa
#+begin_definition
*Why*

We need to represents symbols /i.e./ unique instances (they are only equal to
themselves an nothing else).

*Formation*

#+begin_example
Symbol : Type
#+end_example

*Introduction*

#+begin_example
Symbol#mk : String → Symbol
:name :≡ Symbol#mk("name")
#+end_example

*Elimination*

Behaves like a FinSet where elements are all the symbols that have been introduced so
far.
#+end_definition

* Type

Following the preceding examples of types, we provide the following template to
define new types:

#+ID: 38160003-3d0b-4923-ab0e-d225e3e33658
#+begin_definition
*Why*

Why do we need to introduce this new type?


*Formation*

What is the name of that type?


*Introduction*

How to build instances of that type?


*Elimination*

How to use instances of that type?
#+end_definition

* Propositions as types

#+begin_quote
However, the type-theoretic perspective on proofs is nevertheless different in
important ways.  The basic principle of the logic of type theory is that a
proposition is not merely true or false, but rather can be seen as the collection of
all possible witnesses of its truth.

[…]

propositions are nothing but special types — namely, types whose elements are proofs.

[cite:@HoTT2013]
#+end_quote

#+begin_quote
|-----------------------------------+-------------------|
| English                           | Type Theory       |
|-----------------------------------+-------------------|
| True                              | 1                 |
| False                             | 0                 |
| A and B                           | A × B             |
| A or B                            | A + B             |
| If A then B                       | A → B             |
| A if and only if B                | (A → B) × (B → A) |
| Not A                             | A → 0             |
| For all x : A, P(x) holds         | ∏(x : A),P(x)     |
| There exists x : A such that P(x) | ∑(x : A),P(x)     |
|-----------------------------------+-------------------|

[cite:@HoTT2013]
#+end_quote

* Identity type

#+ID: 24e2fc8c-85be-44ca-b7fc-8b434858f7bd
#+begin_definition
*Why*

The identity type internalizes the notion of equality (or identification)
within the type theory. Given two terms a and b of the same type A, the
identity type a = b is the type of evidences that a and b are equal.

*Formation*

#+begin_example
A : Type
a, b : A
IdA(a, b) : U
a = b :≡ IdA(a, b)
#+end_example


*Introduction*

#+begin_example
refl : Π(a:A), a = a
#+end_example


*Elimination*

#+begin_example
C : A → U
f : ∏(x,y:A)∏(p:x=y),C(x) → C(y)
f(x,x,refl(x)) :≡ id(C(x))
#+end_example


-----


#+begin_example
C : ∏(x,y:A),x=y → U
c : ∏(x:A),C(x,x,refl(x))
f : ∏(x,y:A), ∏(p:x=y), C(x,y,p)
f(x,x,refl(x)) :≡ c(x)
#+end_example
#+end_definition

* List(X)

#+ID: 688dbc9a-9f1f-471f-b362-5703765684c5
#+begin_definition
*Why*

Lists of things are a common data structures, we need a way to represent them.


*Formation*

#+begin_example
X : Type
List(X) : Type
#+end_example


*Introduction*

#+begin_example
[] : List(X)
cons : X List(X) → List(X)
#+end_example


*Elimination*

#+begin_example
C : Type
elim : (c0 : C) (g : X → C → C) → List(X) → C :≡
  f [] :≡ c0
  f cons(x lst) :≡ g x f(lst)
#+end_example


-----


#+begin_example
C : List(X) → Type
c0 : C([])
g : Π(x:X)Π(lst:List(X)), C(lst) → C(cons(x lst))
f : Π(lst:List(X)), C(lst) :≡
  [] ↦ c0
  cons x lst ↦ g x lst f(lst)
#+end_example
#+end_definition

* map

#+ID: dcea748c-4cc7-4fd4-b489-9e2e0ee7cdf4
#+begin_definition
Standard map function.

#+begin_example
map : List(A) (A → B) → List(B) :≡
  as b ↦
    match as
      [] ↦ []
      cons(a as) ↦ cons(b(a) map(as b))
#+end_example
#+end_definition

* Bit

#+ID: 98143a43-8b8b-4712-9630-68885a278503
#+begin_definition
*Why*

Computers manipulates bits, let's represent them.


*Formation*

#+begin_example
Bit : Type
#+end_example


*Introduction*

#+begin_example
0 : Bit
1 : Bit
#+end_example


*Elimination*

#+begin_example
C : Type
c0, c1 : C
f : Bit → C :≡
  0 ↦ c0
  1 ↦ c1
#+end_example


-----


#+begin_example
C : Bit → Type
c0 : C(0)
c1 : C(1)
f : Π(x:Bit), C(x) :≡
  0 ↦ c0
  1 ↦ c1
#+end_example
#+end_definition

* Data

#+ID: f5fda64f-c973-4c7f-a36d-296beb470938
#+begin_definition
*Why*

Computers manipulate /data/ which are just lists of bits.


*Formation*

#+begin_example
Data :≡ List(Bit)
#+end_example
#+end_definition

* Undefined

#+ID: e228fa8f-91d2-4751-8933-5ce1475e1ad0
#+begin_definition
*Why*

Programmning languages have a tendency to represent undefined object, which is to say
to there is something but we have no idea what that is beyond that point.


*Formation*

#+begin_example
Undefined : Type
#+end_example


*Introduction*

#+begin_example
undefined : Undefined
#+end_example


*Elimination*
#+end_definition

* Nothing

#+ID: e9f2605e-c196-4689-8dd6-b6515a7ca84a
#+begin_definition
*Why*

How to represent the absence of a value? By using the unique instance of the Nothing
type, isomorphic to 𝟙.


*Formation*

#+begin_example
Nothing : Type
#+end_example


*Introduction*

#+begin_example
nothing : Nothing
#+end_example


*Elimination*
#+end_definition

* Maybe

#+ID: a489781c-9a92-4c11-9698-81750460e9cf
#+begin_definition
*Why*

Assume that a computers tries to map some data received from the network to some type
using a given program. Assume an injective mapping, then the algorithm might
fail. So, given a piece of data, the algorithm is expected to either provide an
instance of some type or nothing. Let's represent that.


*Formation*

#+begin_example
X : Type
Maybe(X) :≡ Nothing + X
#+end_example


*Construction*

#+begin_example
none :≡ left(nothing)
just(x) :≡ right(x)
#+end_example
#+end_definition

* TODO Vector(X n)

#+ID: f9b8b08e-9b5c-4497-850e-8e8cc0b36aa8
#+begin_definition
*Why*

Finite lists of things that have a known length are common in programming languages,
let's defined them.


*Formation*

#+begin_example
X : Type
n : ℕ
Vector(X n) : Type
#+end_example


*Introduction*

#+begin_example
nil : Vector(X zero)
cons(x lst) : X Vector(X n) → Vector(X n+1)
#+end_example


*Elimination*

🞎
#+end_definition

* TODO index

#+ID: 64e31ad5-c5f5-4d4c-ad2a-adb8bd9f5474
#+begin_definition
*index(lst n)* represents the nth element of lst if any, else undefined.

#+begin_example
index : List(X 0) Nat → X | Undefined
index([] n) :≡ undefined
#+end_example


#+begin_example
index : List(X 1) Nat → X | Undefined
index([x] 0) :≡ undefined
index([x] 1) :≡ x
Given k > 1, then index([x] k) :≡ undefined.
#+end_example


Given index : List(X n) Nat → X | Undefined, lst+x : List(X n+1), and k : Nat, then:
#+begin_example
if k < n+1, then index(lst k) :≡ index(lst k)
if k = n+1, then index(lst n+1) :≡ x
if k > n+1, then index(lst k) :≡ undefined
#+end_example
#+end_definition

* TODO String

#+ID: 5702b0b7-a4bd-4933-bc07-0f30b0f85899
#+begin_definition
#+begin_example
String :≡ List(Nat)
#+end_example
#+end_definition

* TODO Just

#+ID: a6d97a04-6512-4c0b-b4ee-011afac18074
#+begin_definition
#+begin_example
X : Type
Just(X) :≡ 🞎
#+end_example
#+end_definition

* TODO StrictPartialOrder

#+ID: 6086ccfe-0154-4590-b38d-fb994fa0a137
#+begin_definition
#+begin_example
StrictPartialOrder(X) :≡ 🞎
#+end_example
#+end_definition

* TODO Set

#+ID: 6c127151-52d8-4f16-9f8e-9ce43f34b353
#+begin_definition
#+begin_example
X : Type
= : X X → Boolean
= is an equality
Set(X =) :≡
  list : List(X)
  e(i) ∈ list, e(j) ∈ list, i ≠ j, e(i) ≠ e(j)
#+end_example
#+end_definition

* Predicate

#+ID: 7d9319cc-43b6-44a4-909c-bd9de693ee75
#+begin_definition
#+begin_example
Predicate :≡ X → Boolean
#+end_example
#+end_definition

* Language
** cond

To express the fact if a given ~predicate() = true~ holds, then some list of
instructions should be executed, we use the following syntacting form:

#+ID: 3e170749-4e0d-46bf-9587-7ae7bc555cb2
#+begin_definition
#+begin_example
cond
  predicate ↦ instructions
  …
  true ↦ instructions
#+end_example
#+end_definition

** match

To express the fact if some piece of data /x/ has a given form (/i.e./ it matches some
[[https://en.wikipedia.org/wiki/Unification_(computer_science)][pattern]]), then some list of instructions should be executed, potentially using
matched patterns, we use the following syntacting form:

#+ID: 1bc43afe-625d-4ca2-a6fa-913e0a328546
#+begin_definition
#+begin_example
match x
  pattern ↦ instructions
  …
  _ ↦ instructions
#+end_example
#+end_definition

If /x/ does not match any pattern, then it is an error of the author. ~_~ matches
anything. For instance:

#+ID: ec069957-e208-47a8-91ca-f4cd9ad40539
#+begin_instance
#+begin_example
match maybe
  nothing ↦ "nothing"
  just(x) ↦ x
#+end_example
#+end_instance

The meaning should be obvious: if maybe : Maybe(X) ≡ none, then replace the whole
expression by "nothing". If maybe ≡ just(x), then replace the whole expression by
x. Patterns may be extended by predicates using /guards/. For instance:

#+ID: b5b6980d-fd98-4296-9fa6-996f5eacce12
#+begin_definition
#+begin_example
match x
  pattern when predicate ↦ instructions
  …
#+end_example
#+end_definition

* Bibliography

#+print_bibliography:
